<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="UseCases\Admin\" />
	</ItemGroup>

</Project>