CREATE TABLE WebhookConfig (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    EmpresaId UNIQUEIDENTIFIER NOT NULL,
    Nome NVARCHAR(255) NOT NULL,
    Url NVARCHAR(500) NOT NULL,
    Evento NVARCHAR(100) NOT NULL,
    TokenSegredo NVARCHAR(500) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    DataCriacao DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_WebhookConfig_Empresa FOREIGN KEY (EmpresaId) REFERENCES Empresa(Id)
);
