CREATE TABLE Produto (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    EmpresaId UNIQUEIDENTIFIER NOT NULL,
    Nome NVARCHAR(255) NOT NULL,
    Descricao NVARCHAR(1000) NULL,
    Preco DECIMAL(18, 2) NOT NULL,
    ImagemUrl NVARCHAR(500) NULL,
    LinkUrl NVARCHAR(500) NULL,
    Categoria NVARCHAR(100) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    DataCriacao DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Produto_Empresa FOREIGN KEY (EmpresaId) REFERENCES Empresa(Id)
);
